config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :images, only: :update
  end
  resources :folders
  root "images#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/controllers/api/images_controller.rb
module Api
  class ImagesController < ApplicationController

    def update
      @image = Image.find params[:id]
      @image.update! title: params[:image][:title].strip
      head :ok
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder!, only: %i[edit update]

  def index
    @folders = Folder.order created_at: :desc
  end

  def new
    @folder = Folder.new
  end


  def create
    @folder = Folder.new folder_params

    if @folder.save
      # redirect_to folders_path
      else
        render :new

    end

  end


  def edit; end


  def update
    if @folder.update folder_params
      redirect_to folders_path
      else
        render :edit

    end

  end

  private

  def set_folder!
    @folder = Folder.find params[:id]

  end

  def folder_params
    params.require(:folder).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  @images = Image.all
  @images = Image.order id: :desc

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/folders/_add_folder.html.erb
<%= turbo_frame_tag Folder.new do %>
  <%= link_to 'Add folder', new_folder_path, class: 'btn btn-primary' %>
<% end %>

app/views/folders/_folder.html.erb
<%= turbo_frame_tag folder do %>
  <section class="mb-4">
    <h2><%= folder.title  %> </h2>
    <p> <%= folder.description  %> </p>
    <%= link_to 'Edit', edit_folder_path(folder), class: 'btn btn-primary' %>
  </section>
<% end %>

app/views/folders/_form.html.erb
<%= turbo_frame_tag folder do %>
  <%= form_with model: folder do |f| %>
    <%= render 'shared/errors', object: folder %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <%end%>
<%end%>

app/views/folders/create.turbo_stream.erb
 <%= turbo_stream.replace Folder.new , partial: 'add_folder' %>
<%=turbo_stream.after Folder.new , render(@folder) %>

app/views/folders/edit.html.erb
<h1>Edit folder</h1>
<%= render 'form', folder: @folder%>

app/views/folders/index.html.erb
<h1> Foders </h1>
<%= render 'add_folder' %>
<%= render @folders %>

app/views/folders/new.html.erb
<h1> New Folder </h1>
<%= render 'form', folder: @folder%>

app/views/home/index.html.erb
<h1>Home#index</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<p>Find me in app/views/home/index.html.erb</p>
<div class="modal fade" id="exampleModalXl" tabindex="-1" aria-labelledby="exampleModalXlLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-4" id="exampleModalXlLabel">Extra large modal</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModalXl">Extra large modal</button>

app/views/images/index.html.erb
<h1> Images </h1>
<% @images.each do |image| %>
  <%= tag.section class: 'my-5', 
  data: {controller: 'images toast', action: 'images:copy->toast#show', 
  'images-loading-class': 'disabled' , 'images-id-value': image.id} do %>
    <%= image_tag image.url, class: 'img-thumbnail rounded d-block',
            alt: image.title, data: {'action': 'click->images#getUrl',
            'images-target': 'image'}  %>
  <% end %>
<% end %>
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="copyToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <strong class="me-auto">Bootstrap</strong>
      <small>11 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      Hi
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apphw</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg|%>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>